---
# Name for the created server profile template
server_profile_template: SPT0

# Name for the created server profile
server_profile: server0

# Name of the enclosure group
enclosure_group: EG

# Name of the server hardware type
server_hardware_type: SY 480 Gen9 2

# Name of the server hardware
server_hardware: 0000A66101, bay 8

# Name of the network
network: Prod_1101
