---
# Name for the created server profile template
server_profile_template: SPT5

# Name for the created server profile
server_profile: server5

# Name of the enclosure group
enclosure_group: EG

# Name of the server hardware type
server_hardware_type: SY 660 Gen10 1

# Name of the server hardware
server_hardware: 0000A66102, bay 6

# Name of the network
network: Prod_1101
