---
# Name for the created server profile template
server_profile_template: SPT3

# Name for the created server profile
server_profile: server3

# Name of the enclosure group
enclosure_group: EG

# Name of the server hardware type
server_hardware_type: SY 480 Gen10 1

# Name of the server hardware
server_hardware: 0000A66103, bay 11

# Name of the network
network: Prod_1101
